id: ICDC3D9C7
ocr_import_info:
  timestamp: '2023-09-29T16:05:27.404019+00:00'
  batch_id: batch-3941
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-29 19:05:30.518308+00:00
last_modified: 2023-09-29 19:05:30.518315+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC48
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1AC48
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་རྣམ་འགྲེལ་ཊཱིཀ་ཆེན་རིགས་པའི་རྒྱ་མཚོ། ༼སྟོན་ཆ༽ ༼སྨད་ཆ༽
  languages:
  - bo
  author: མཁས་གྲུབ་རྗེ་དགེ་ལེགས་དཔལ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.9919309577343357
  ocr_word_median_confidence_index: 0.99999994
bases:
  I2PD18167:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18167
      total_pages: 606
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2PD18167.txt
    statistics:
      ocr_word_median_confidence_index: 0.99999994
      ocr_word_mean_confidence_index: 0.991235360803634
  I2PD18166:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18166
      total_pages: 550
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD18166.txt
    statistics:
      ocr_word_median_confidence_index: 0.99999994
      ocr_word_mean_confidence_index: 0.9926946961755446
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
